name: Release new version

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: syb-production-platform

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/399860310130/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "wgc-sa@syb-production-platform.iam.gserviceaccount.com"

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login gcr.io -u oauth2accesstoken --password-stdin

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/syb-common-images/icecast-exporter:${GITHUB_SHA}" \
            .
      # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: |-
          docker push "gcr.io/syb-common-images/icecast-exporter:${GITHUB_SHA}"
